Created more utilites

diff --git a/run/run-onnode b/run/run-onnode
--- a/run/run-onnode
+++ b/run/run-onnode
@@ -32,19 +32,14 @@ case $1 in
         done
         
         # Choosing the dataset.
-        case $2 in
-            "fb")
-                DATASET=/filepool/fb/parts_${NDS}/facebook_combined.txt.bsnap; IK=FB
-                ;;
-            "reddit")
-                DATASET=/filepool/reddit/parts_${NDS}/reddit.graph.bsnap;      IK=RD
-                ;;
-            *)
-                DATASET=/filepool/fb/parts_${NDS}/facebook_combined.txt.bsnap; IK=FB
-                ;;
-        esac
+        if [[ ! -d /filepool/$2 ]]; then
+            echo "Dataset $2 not found under '/filepool' (at least on master node)."
+            echo "Please prepare the dataset correctly."
+            exit 1
+        fi
 
-        FEATUREFILE=$( dirname ${DATASET} )/../features.bsnap
+        DATASET=/filepool/$2
+
         LAYERFILE=${HOME}/layerconfig
 
         # Minor options.
@@ -71,8 +66,8 @@ case $1 in
         dsh -f ../dshmachines -c "mkdir ${TMPFILEDIR}"
 
         # Run the command on all dsh machines.
-        echo "DSH command: ./build/graphserver --graphfile ${DATASET} --featuresfile ${FEATUREFILE} --layerfile ${LAYERFILE} --dataserverport ${GPORT} --coordserverip ${CSERVERIP} --coordserverport ${CPORT} --undirected ${UNDIRECTED} --tmpdir=${TMPFILEDIR} --cthreads ${COMP_THREADS} --dthreads ${COMM_THREADS}"
-        dsh -f ../dshmachine -c "cd ${HOME}/gnn-lambda && ./build/graphserver --graphfile ${DATASET} --featuresfile ${FEATUREFILE} --layerfile ${LAYERFILE} --dataserverport ${GPORT} --coordserverip ${CSERVERIP} --coordserverport ${CPORT} --undirected ${UNDIRECTED} --tmpdir=${TMPFILEDIR} --cthreads ${COMP_THREADS} --dthreads ${COMM_THREADS}" 1> /dev/null 2>> ${LOGFILE}
+        echo "DSH command: ./build/graphserver --graphfile ${DATASET}/parts_${NDS}/graph.bsnap --featuresfile ${DATASET}/features.bsnap --layerfile ${LAYERFILE} --dataserverport ${GPORT} --coordserverip ${CSERVERIP} --coordserverport ${CPORT} --undirected ${UNDIRECTED} --tmpdir=${TMPFILEDIR} --cthreads ${COMP_THREADS} --dthreads ${COMM_THREADS}"
+        dsh -f ../dshmachine -c "cd ${HOME}/gnn-lambda && ./build/graphserver --graphfile ${DATASET}/parts_${NDS}/graph.bsnap --featuresfile ${DATASET}/features.bsnap --layerfile ${LAYERFILE} --dataserverport ${GPORT} --coordserverip ${CSERVERIP} --coordserverport ${CPORT} --undirected ${UNDIRECTED} --tmpdir=${TMPFILEDIR} --cthreads ${COMP_THREADS} --dthreads ${COMM_THREADS}" 1> /dev/null 2>> ${LOGFILE}
         
         # Gather the output files.
         OUTFILEDIR=${HOME}/outfiles/${RUN_MARK}.${IK}
